framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async: # Define RabbitMQ transport
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5               # Maximum number of retries
                    delay: 1000                  # Initial delay in milliseconds
                    multiplier: 2                # Exponential backoff multiplier
                    max_delay: 60000             # Maximum delay in milliseconds
                options:
                    exchange:
                        name: logs
                    queues:
                        chunk_processing_queue:
                            arguments:
                                x-dead-letter-exchange: 'logs'
                                x-dead-letter-routing-key: 'dead_letters'
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Application\Message\ChunkProcessingMessage': async
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
