version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logparser
    volumes:
      - .:/app:delegated
      - ./var:/app/var
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      APP_ENV: dev

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.docker

volumes:
  db_data:
