version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logparser
    volumes:
      - .:/app:delegated
      - ./var:/app/var
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  messenger-worker:
    build:
      context: .
    container_name: app-messenger-worker
    command: php bin/console messenger:consume async --memory-limit=128M
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}

volumes:
  db_data:
